---
client:
  address: "127.0.0.1:8787"  # HTTPS' TCP address
  pkey: 7abY7sBqNrtN5Z+NElo19hBDO1ixZ1+EGrrMq0gAjeE=
server:
  address: "127.0.0.1:9090"  # Remote server's UDP address
  protocol: basic 
  pkey: 7abY7sBqNrtN5Z+NElo19hBDO1ixZ1+EGrrMq0gAjeE=  
