---
client:
  enabled: true
  host: 127.0.0.1
  port: 8787
  protocal: basic 
  pkey: 7abY7sBqNrtN5Z+NElo19hBDO1ixZ1+EGrrMq0gAjeE=
server:
  enabled: true
  host: 127.0.0.1
  port: 9090
  protocal: basic 
  pkey: 7abY7sBqNrtN5Z+NElo19hBDO1ixZ1+EGrrMq0gAjeE=  